### PR TITLE
🛠 fix 404 page not working

### PR DESCRIPTION
**Pull request by mohammedmoutawakkil**
🛠 fix 404 page not working

### CODE REVIEW

**Comment by imbhargav5** [comment]
This is amazing! Thank you @mohammedmoutawakkil 🙏

**Comment by imbhargav5** [comment]
Looks like eslint is the only thing failing. Once that is fixed, I will merge this PR.

**Comment by imbhargav5** [comment]
Never mind. I will fix this.

**Comment by mohammedmoutawakkil** [comment]
@imbhargav5 glad to contribute to this work ✌️

**Pull request merged**
